### ISSUE TITLE
Chat Functional Update Proposal

### ISSUE THREAD

**Issue by sethwhitaker** [sethwhitaker/konnekt4#93]
Update the chat query to get all chats vs only those which happened during current session.

**Pros**
- Dont miss chats

**Cons**
- Chat box can get too long unless we also implement a lazy load for older chats.

**To-Do**
- [ ] Update query to `get_all()`
- [ ] Lazy Load old chats
- [ ] New Chat Notifications
- [ ] Server Web-Sockets Push functionality.
- [ ] When refreshing box with new chats, only `append` new chats, dont re-write whole list.
